name: CI

on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Install dependencies
        run: |
          xcodebuild -resolvePackageDependencies -project recipes-uikit.xcodeproj -scheme recipes-uikit

      - name: Build and run tests
        run: |
          xcodebuild clean build test \
          -project recipes-uikit.xcodeproj \
          -scheme recipes-uikit \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0' \
          ONLY_ACTIVE_ARCH=NO \
          -allowProvisioningUpdates | xcpretty